# Generated by Django 4.1.7 on 2023-02-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('isDone', models.BooleanField()),
            ],
        ),
    ]
